{% set name = "jupyter_resource_usage_proxy" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_resource_usage_proxy-{{ version }}.tar.gz
  sha256: de9d7f1fe6a34f43369d7085bd29bb5d64e1195382832795c94342dcba50d9cb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - jupyter_server >=1.0.0
    - httpx >=0.23.1

test:
  requires:
    - pip
  imports:
    - jupyter_resource_usage_proxy
  commands:
    - pip check

about:
  summary: A Jupyter Server Extension Proxying Resource Usage.
  license: MIT
  license_file: LICENSE
  home: https://github.com/davidbrochart/jupyter-resource-usage-proxy

extra:
  recipe-maintainers:
    - benmoss
    - davidbrochart
